### PR TITLE
Fix Content resolver not working

### PR DESCRIPTION
**Pull request by greenart7c3**
## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by greenart7c3** [comment]
When pressing the amber button or theres another place that call this?

**Comment by KoalaSat** [comment]
> When pressing the amber button or theres another place that call this?

When pressing the button, also I realized it fails when it tries to sign the with event, so basically everytime the app tries to interact with Ember

**Comment by greenart7c3** [comment]
The error is not happening with me

**Comment by KoalaSat** [comment]
Okay then, let's create a pre-release and test it out, thank you!!

**Pull request merged**
